on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          path: dist
          ref: gh-pages
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Build
        run: |-
          cd src
          env GOOS=js GOARCH=wasm go build -o ../dist/lifegame.wasm github.com/backpaper0/lifegame

      - name: Copy wasm_exec.js
        run: |-
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js dist/

      - name: Commit and Push
        run: |-
          cd dist
          git config user.email "209262+backpaper0@users.noreply.github.com"
          git config user.name "Uragami Taichi"
          git add .
          git commit -m "Publish new version"
          git push origin gh-pages